---
title: "RNAseq"
author: "Howard Cen"
date: "2024-11-16"
output: html_document
---

```{r}

library(tidyverse)
#BiocManager::install("DESeq2")
library("DESeq2")

#BiocManager::install("org.Hs.eg.db")
library(org.Hs.eg.db)

#BiocManager::install("clusterProfiler")
#BiocManager::install("ReactomePA")
library("clusterProfiler")
library("ReactomePA")

#install.packages("devtools") # most recent version of complexheatmap
#library(devtools)
#install_github("jokergoo/ComplexHeatmap")
library(ComplexHeatmap)
library(circlize) 
#install.packages("gridtext")
library(gridtext)
library(scales)

#install.packages("ggrepel")
library(ggrepel) # https://ggrepel.slowkow.com/articles/examples.html

setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) ##Set working directory to where this file is.
getwd()
```


```{r processing}

#files <- list.files(path="input", pattern = "genes\\.sf$") # List all files ending with genes.sf

df1 <- read.delim("input/D1-JZ-091124_711853222.quant.genes.sf") %>%
  mutate(ENSG = gsub("\\..*","", Name)) %>%
  select(all_of(c('Name', 'ENSG','NumReads'))) %>%
  rename(DMSO_1 = NumReads)


df2 <- read.delim("input/D2-JZ-091124_711853225.quant.genes.sf") %>%
  mutate(ENSG = gsub("\\..*","", Name)) %>%
  select(all_of(c('Name', 'ENSG','NumReads'))) %>%
  rename(DMSO_2 = NumReads)

df3 <- read.delim("input/D3-JZ-091124_711853224.quant.genes.sf") %>%
  mutate(ENSG = gsub("\\..*","", Name)) %>%
  select(all_of(c('Name', 'ENSG','NumReads'))) %>%
  rename(DMSO_3 = NumReads)

df4 <- read.delim("input/X1-JZ-091124_711853255.quant.genes.sf") %>%
  mutate(ENSG = gsub("\\..*","", Name)) %>%
  select(all_of(c('Name', 'ENSG','NumReads'))) %>%
  rename(ISX_1 = NumReads)

df5 <- read.delim("input/X2-JZ-091124_711853223.quant.genes.sf") %>%
  mutate(ENSG = gsub("\\..*","", Name)) %>%
  select(all_of(c('Name', 'ENSG','NumReads'))) %>%
  rename(ISX_2 = NumReads)

df6 <- read.delim("input/X3-JZ-091124_711853252.quant.genes.sf") %>%
  mutate(ENSG = gsub("\\..*","", Name)) %>%
  select(all_of(c('Name', 'ENSG','NumReads'))) %>%
  rename(ISX_3 = NumReads)

df <- full_join(df1,df2) %>%
  full_join(df3)%>%
  full_join(df4)%>%
  full_join(df5)%>%
  full_join(df6)

View(df)

write.table(df, "output/rawcounts.txt", row.names = F)


```

```{r processing}
df <- read.table("output/rawcounts.txt", header = T)
dup <- df %>% group_by(ENSG) %>% filter(n()>1)
View(dup)
#aggr <- dup %>% group_by(ENSG) %>% summarise(across(everything(), max, na.rm = TRUE))

length(unique(dup$ENSG)) # 45 genes

df <- filter(df, !grepl("PAR_Y", Name))

raw <- df %>% column_to_rownames("ENSG") %>% select(-"Name")
View(raw)

raw.counts <- round(raw,0) # Counts are not integers. Rounded up because DESeq2 requires integers.
raw.counts <- raw.counts[rowSums(raw.counts)!=0,] # Counts<0.5 became 0. Remove genes with all 0 again
dim(raw.counts) # 32063 genes left
summary(colSums(raw.counts))
#    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
#14990023 17462594 19239534 18960576 20746653 22175062 


# meta data

sample <- colnames(raw.counts)
group <- gsub("_[0-9]","", sample) 
group <- gsub ("ISX", "ISX9", group)
meta.data <- data.frame(sample, group)
row.names(meta.data) <- meta.data$sample
all(colnames(raw.counts)==rownames(meta.data))
meta.data$group <- factor(meta.data$group, levels=c("DMSO",
                                                    "ISX9"))
View(meta.data)

```

```{r}
# DESeq2 and PCA =============

count.data.set <- DESeqDataSetFromMatrix(countData=raw.counts, 
                                         colData=meta.data, design= ~ group) 

# Filter out low count
nrow(count.data.set) # 32063 genes

keep <- rowSums(counts(count.data.set)>=5) >= ncol(raw.counts)*0.5  # Keep genes with >5 counts in at least 50% samples. 
count.filter <- count.data.set[keep,]
nrow(count.filter) # 20660 genes left.

# create DESeq object
count.data.set.object <- DESeq(count.filter)

# normalized counts (without VST)
dds <- estimateSizeFactors(count.data.set.object)
normalized.counts <- counts(dds, normalized=TRUE)
write.csv(normalized.counts, file="output/norm_counts.csv")

# normalized  VST counts
vsd <- vst(count.data.set.object)
norm.data = assay(vsd)
write.csv(norm.data,file="output/norm_VST.csv")


# cluster
sampleDists <- dist(t(norm.data),  method = "euclidean") # "euclidean", "maximum", "manhattan", "canberra", "binary" or "minkowski"
clusters=hclust(sampleDists)
plot(clusters)

# PCA
# modify the PCA function to change format ---------------------------

getMethod("plotPCA","DESeqTransform")
plotPCA.format <- function (object, ...) 
{
  .local <- function (object, intgroup = "condition", 
                      ntop = 500, returnData = FALSE) 
  {
    rv <- rowVars(assay(object))
    select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                       length(rv)))]
    pca <- prcomp(t(assay(object)[select, ]))
    percentVar <- pca$sdev^2/sum(pca$sdev^2)
    if (!all(intgroup %in% names(colData(object)))) {
      stop("the argument 'intgroup' should specify columns of colData(dds)")
    }
    intgroup.df <- as.data.frame(colData(object)[, intgroup, 
                                                 drop = FALSE])
    group <- if (length(intgroup) > 1) {
      factor(apply(intgroup.df, 1, paste, collapse = ":"))
    }
    else {
      colData(object)[[intgroup]]
    }
    d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], group = group, 
                    intgroup.df, name = colnames(object))
    if (returnData) {
      attr(d, "percentVar") <- percentVar[1:2]
      return(d)
    }
    ggplot(data = d, aes_string(x = "PC1", y = "PC2", 
                                fill = "group")) + geom_point(size = 4, shape=21,alpha=0.6) + 
      xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
      ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + 
      coord_fixed() #+  geom_label_repel((aes(label=sample)))
  }
  .local(object, ...)
}


#------------------------------------------------------------------------

# use color blind friendly palette
cbPalette <- c("#E69F00", #lightorange
               "#56B4E9", #blue
               "#D55E00", #darkorange
               "#009E73", #green
               "#CC79A7", #magenta
               "#0072B2", #darkblue
               "#F0E442", #yellow
               "#999999" #grey
)


# plot PCA

p <- plotPCA.format(vsd, intgroup=c("group"))+ 
  geom_text_repel(aes(label=colData(vsd)$sample),size=3,
                  color="grey50",
                  box.padding   = 0.4,
                  point.padding = 0,
                  #force=1,
                  #force_pull=10,
                  max.overlaps = Inf, # always show all label, regardless of overlap
                  #min.segment.length = 0, # always draw line
                  segment.color = 'grey50')+
  scale_fill_manual(values=cbPalette) +
  theme_bw()+
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.x  = element_blank(),
        panel.grid.major.x  = element_blank(),
        axis.text = element_text(size = 13),
        axis.title = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_blank()
  )+
  theme(aspect.ratio=1/1)

p

# FYI, this is the default function plotPCA()
#plotPCA(vsd, intgroup=c("group"))

ggsave(plot = p, filename="figures/PCA_label.pdf",width=13,height=10,units="cm")
ggsave(plot = p, filename="figures/PCA_label.svg",device= svg,width=13,height=10,units="cm")

```

```{r}

# sample matrix

library("RColorBrewer")
sampleDistMatrix <- as.matrix( sampleDists )
View(sampleDistMatrix)
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(sampleDistMatrix,
         legend = T,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colors)

pDist<-pheatmap(sampleDistMatrix,
                legend = F,
                clustering_distance_rows = sampleDists,
                clustering_distance_cols = sampleDists,
                cellwidth = 20, cellheight = 20,
                treeheight_row=10,
                treeheight_col=10,
                col = colors)

pDist

# ran in console
{png(file = "figures/dist_matrix.png",
    width = 10, 
    height = 10,
    res  =  400,
    unit = "cm")

pDist

dev.off()}
```

png(file = "figures/dist_matrix.png",
      width = 10, 
      height = 10,
      res  =  400,
      unit = "cm")
     
pDist
     
dev.off()


```{r}
# plot the VST normalized counts on heatmap =============


View(norm.data)
m<- norm.data

#m <- as.matrix(as.data.frame(lapply(m.anno, as.numeric),check.names=F))
View(m)
m.z <- t(scale(t(m))) #%>% as.data.frame()
View(m.z)
colnames(m.z)
ceiling(max(abs(m.z)))
#m.z[m.z>5] <- NA
#m.z <- t(scale(t(m.z)))
#m.z[is.na(m.z)] <- 5

number_of_d <- length(grep("DMSO", colnames(m.z)))
number_of_x <- length(grep("ISX", colnames(m.z)))

end_index_d <- grep("DMSO", colnames(m.z))[number_of_d]
end_index_x <- grep("ISX", colnames(m.z))[number_of_x]

###

#heatmap_list_total <- 
heatmap.all <- Heatmap(m.z, #matrix_Z_score_total,
                         name = "Z score",
                         show_row_names = FALSE,
                         show_column_names = FALSE,
                         show_row_dend = TRUE,
                         # row_labels = gt_render(m.anno$protein.symbol),
                         row_names_gp = gpar(fontsize = 8),
                         column_names_side = "top",
                         column_dend_side = "bottom",
                     clustering_distance_rows = "euclidean",
                     clustering_method_rows = "ward.D2",
                     row_dend_side = "left",
                     row_dend_width = unit(5, "mm"),
                         layer_fun = function(j, i, x, y, width, height, fill) {
                           mat = restore_matrix(j, i, x, y)
                           ind = unique(c(mat[, c(end_index_d#, 
                                                  #end_index_bud
                                                  )]))
                           grid.rect(x = x[ind] + unit(0.5/ncol(m.z), "npc"), 
                                     y = y[ind], 
                                     width = unit(0.03, "inches"), 
                                     height = unit(1/nrow(m.z), "npc"),
                                     gp = gpar(col = "white")
                           )
                         },
                         col = colorRamp2(c(-3,0,3), c("blue", "white", "red")),
                         top_annotation = columnAnnotation(empty = anno_empty(border = FALSE
                                                                              , height = unit(12, "mm")
                         )),
                         
                         column_order = 1:ncol(m.z),
                         height = 
                           
                           
                           unit(80, "mm"), 
                         
                         width = ncol(m.z)*unit(6, "mm"),
                         border_gp = gpar(col = "black"),
                         show_heatmap_legend = TRUE,
                         heatmap_legend_param = list(
                           title = "Z-score",
                           title_position = "topleft",
                           legend_height = unit(4, "cm")))

draw(heatmap.all)
#

png(file = "figures/heatmap_all.png",
    width = 3, 
    height = 4, 
    units = "in", res = 600)

{pdf(file = "figures/heatmap_all.pdf",
    width = 3, 
    height = 4)

draw(heatmap.all)

#
seekViewport("annotation_empty_1")
loc1 = deviceLoc(x = unit(0, "npc"), y = unit(0, "npc"))
loc2 = deviceLoc(x = unit(1, "npc"), y = unit(1, "npc"))

####Condition labels

#Condition label 1


grid.rect(x = (loc2$x - loc1$x)*(end_index_d)/2/ncol(m.z),
          y = 0,
          width = (loc2$x - loc1$x)*(number_of_d)/ncol(m.z), 
          height = (loc2$y - loc1$y)/2,
          just = c("center", "bottom"),
          gp = gpar(fill = alpha(cbPalette[1], 0.5),
                    col = alpha(cbPalette[1], 0.5)
          )
)
grid.text(expression("DMSO"), 
          x = (loc2$x - loc1$x)*(end_index_d)/2/ncol(m.z),
          y = 0.25,
          just = c("center", "center"),
          gp = gpar(fontsize = 11,
                    col = "black"))

#Condition label 2

grid.rect(x = (loc2$x - loc1$x)*(end_index_d + 
                                   end_index_x)/2/ncol(m.z),
          y = 0,
          width = (loc2$x - loc1$x)*(number_of_x)/ncol(m.z), 
          height = (loc2$y - loc1$y)/2,
          just = c("center", "bottom"),
          gp = gpar(fill = alpha(cbPalette[2], 0.5),
                    col = alpha(cbPalette[2], 0.5)
          )
)
grid.text(expression("ISX9"), 
          x = (loc2$x - loc1$x)*(end_index_d + 
                                   end_index_x)/2/ncol(m.z),
          y = 0.25,
          just = c("center", "center"),
          gp = gpar(fontsize = 11))





###Top label gaps

#Vertical lines
grid.rect(x = end_index_d/ncol(m.z),
          y = 0,
          height = (loc2$y - loc1$y)/2,
          width = unit(0.03, "inches"),
          just = c("center", "bottom"),
          gp = gpar(fill = "white", 
                    col = "white", 
                    lwd = 1
          ))


dev.off()}
```


```{r}

# DEG ============

#resultsNames(count.data.set.object)


#res <- results(count.data.set.object, contrast=c("group",exp,ctrl),alpha=0.05)
res <- results(count.data.set.object, contrast=c("group","ISX9","DMSO"),alpha=0.05)


# save result summary
summary(res) 
out <- capture.output(summary(res))
cat("ISX9 vs DMSO", out, file="output/results_summary.txt", sep="\n", append=TRUE)

# save results - all genes
res <-  na.omit(res) # omit NA
res  <-  res[order(res$padj),] 
res <- as.data.frame(res)

res$ENSG <- rownames(res)
res$entrez <- mapIds(org.Hs.eg.db, keys=res$ENSG, column="ENTREZID", keytype="ENSEMBL", multiVals="first")
res$symbol <- mapIds(org.Hs.eg.db, keys=res$ENSG, column="SYMBOL", keytype="ENSEMBL", multiVals="first")
res$fullname <- mapIds(org.Hs.eg.db, keys=res$ENSG, column="GENENAME", keytype="ENSEMBL", multiVals="first")

#columns(org.Hs.eg.db)

View(res)
write.table(res, sep="\t",file=paste0("output/ISX_DE_results.txt"), row.names=TRUE,col.names=NA,quote=FALSE)
write.csv(res, "output/ISX_DE_results.csv", row.names = F)
```

```{r ORA}
res <- read.delim(file="output/ISX_DE_results.txt", row.names = 1)

# save results - significant genes (DEG)
res.sig <- res[res$padj <= 0.05,]
dim(res.sig) # 6882 DE

#write.table(res.sig, sep="\t",file=paste0("output/Results_DE.txt"), row.names=TRUE,col.names=NA,quote=FALSE)

res.up <- res.sig[res.sig$log2FoldChange>0,]
res.down <- res.sig[res.sig$log2FoldChange<0,]

dim(res.up) #  3600 up
dim(res.down) # 3282 down


```

```{r selected-volcano}
# Selected gene list ===============

selected <- c('PDX1', 'NKX6.1', 'SOX9', 'GP2', 'F2', 'ONECUT1', 'SOX17', 'NEUROG3', 'NEUROD1', 'CHGA', 'ISL1', 'INS', 'GCG', 'SST', 'ALB', 'LEFTY1', 'GDF3', 'CXCR4', 'ONECUT3', 'PROX1', 'MKI67', 'INSM1', 'FOXA2')
```

```{r selected-heatmap}
# Selected gene list ===============

selected <- c('PDX1', 'NKX6.1', 'SOX9', 'GP2', 'F2', 'ONECUT1', 'HNF4A', 'SOX17', 'PTF1A', 'NEUROG3', 'NEUROD1', 'CHGA', 'SYP', 'ISL1', 'INS', 'GCG', 'SST', 'GHRL', 'GDF3', 'CXCR4', 'ONECUT3', 'PROX1', 'MKI67', 'INSM1', 'FOXA2', 'GATA6', 'KRT19', 'PCDH1', 'MMP2', 'CALB1', 'CD274', 'GLP1R', 'CPE', 'IRX2', 'SLIT1', 'SLIT3', 'ROBO3', 'EPHB1', 'EPHB3', 'FGF2', 'EPHA10', 'CD47', 'DPPA4', 'COL1A2', 'CRABP1', 'FLT4', 'LEFTY1', 'ALB', 'UCN3', 'RBP4', 'GRIN2A', 'NKX2.2', 'ERBB3', 'NOTCH1', 'NOTCH3', 'HES1', 'HEY1', 'SLC30A8', 'CDH1', 'KRT18', 'CTNNB1', 'PAX6', 'YAP1', 'MUC1', 'FOXO1', 'KLF6', 'RHOB', 'KRT18', 'KRT8', 'MCM2', 'MCM3')




selected[-which(selected %in% res$symbol)]
# "MAFA"        "CFTR"        "NKX2-5"      "CD90 (THY1)" are not in RNAseq due to low detection

raw.counts[c(selected[-which(selected %in% res$symbol)],"THY1"),]
# body1 body2 body3 body4 bud1 bud2 bud3 bud4
# MAFA       1     1     1     1    2    1    2    1
# CFTR       1     1     1     2    1    1    2    0
# NKX2-5     2     1     2     2    1    0    0    0
# NA        NA    NA    NA    NA   NA   NA   NA   NA
# THY1      33    31    38    36    7    6    7    2

selected.new <- c(selected[which(selected %in% res$symbol)],"THY1")

selected.ns <- selected.new[-which(selected.new %in% res.sig$symbol)]
# "KRT19" "AMY2B" "PBX2"  "SLIT3" are not DE

selected.sig <- selected.new[-which(selected.new %in% selected.ns)]

# plot the selecte gene (VST normalized counts) on heatmap ------

# plot selected genes only
norm.data <- read.delim("output/Norm_data.txt", row.names = 1)
View(norm.data)
m<- norm.data[selected.sig,]

# plot selected genes on the heatmap of all DE genes
m <- norm.data[res.sig$symbol,]
at <- match(selected.new,rownames(m))
labels <- selected.new

#m <- as.matrix(as.data.frame(lapply(m.anno, as.numeric),check.names=F))
View(m)
m.z <- t(scale(t(m))) #%>% as.data.frame()
View(m.z)
colnames(m.z)
ceiling(max(abs(m.z)))

number_of_body <- length(grep("body", colnames(m.z)))
number_of_bud <- length(grep("bud", colnames(m.z)))

end_index_body <- grep("body", colnames(m.z))[number_of_body]
end_index_bud <- grep("bud", colnames(m.z))[number_of_bud]

# use color blind friendly palette
cbPalette <- c("#E69F00", #lightorange
               "#56B4E9", #blue
               "#D55E00", #darkorange
               "#009E73", #green
               "#CC79A7", #magenta
               "#0072B2", #darkblue
               "#F0E442", #yellow
               "#999999" #grey
)

## selected genes
heatmap.b <- Heatmap(m.z, #matrix_Z_score_total,
                     name = "Z score",
                     
                     show_row_names = TRUE,
                     
                     show_column_names = FALSE,
                     show_row_dend = TRUE,
                     row_labels = gt_render(row.names(m)),
                     row_names_gp = gpar(fontsize = 8),
                     column_names_side = "top",
                     column_dend_side = "bottom",
                     clustering_distance_rows = "euclidean",
                     clustering_method_rows = "ward.D2",
                     row_dend_side = "left",
                     row_dend_width = unit(5, "mm"),
                     layer_fun = function(j, i, x, y, width, height, fill) {
                       mat = restore_matrix(j, i, x, y)
                       ind = unique(c(mat[, c(end_index_body#, 
                                              #end_index_bud
                       )]))
                       grid.rect(x = x[ind] + unit(0.5/ncol(m.z), "npc"), 
                                 y = y[ind], 
                                 width = unit(0.03, "inches"), 
                                 height = unit(1/nrow(m.z), "npc"),
                                 gp = gpar(col = "white")
                       )
                     },
                     col = colorRamp2(c(-3,0,3), c("blue", "white", "red")),
                     top_annotation = columnAnnotation(empty = anno_empty(border = FALSE
                                                                          , height = unit(12, "mm")
                     )),
                     
                     column_order = 1:ncol(m.z),
                     height = 
                       
                       unit(180, "mm"), 
                     
                     width = ncol(m.z)*unit(6, "mm"),
                     border_gp = gpar(col = "black"),
                     show_heatmap_legend = TRUE,
                     heatmap_legend_param = list(
                       title = "Row z-score",
                       title_position = "topleft",
                       legend_height = unit(4, "cm"))) 
draw(heatmap.b)

### all DE genes + label selected genes
heatmap.b <- Heatmap(m.z, #matrix_Z_score_total,
                     name = "Z score",
                     
                     #show_row_names = TRUE,
                     show_row_names = FALSE,
                     
                     show_column_names = FALSE,
                     show_row_dend = TRUE,
                     row_labels = gt_render(row.names(m)),
                     row_names_gp = gpar(fontsize = 8),
                     column_names_side = "top",
                     column_dend_side = "bottom",
                     clustering_distance_rows = "euclidean",
                     clustering_method_rows = "ward.D2",
                     row_dend_side = "left",
                     row_dend_width = unit(5, "mm"),
                     layer_fun = function(j, i, x, y, width, height, fill) {
                       mat = restore_matrix(j, i, x, y)
                       ind = unique(c(mat[, c(end_index_body#, 
                                              #end_index_bud
                       )]))
                       grid.rect(x = x[ind] + unit(0.5/ncol(m.z), "npc"), 
                                 y = y[ind], 
                                 width = unit(0.03, "inches"), 
                                 height = unit(1/nrow(m.z), "npc"),
                                 gp = gpar(col = "white")
                       )
                     },
                     col = colorRamp2(c(-3,0,3), c("blue", "white", "red")),
                     top_annotation = columnAnnotation(empty = anno_empty(border = FALSE
                                                                          , height = unit(12, "mm")
                     )),
                     
                     column_order = 1:ncol(m.z),
                     height = 
                       
                       unit(180, "mm"), 
                     
                     width = ncol(m.z)*unit(6, "mm"),
                     border_gp = gpar(col = "black"),
                     show_heatmap_legend = TRUE,
                     heatmap_legend_param = list(
                       title = "Z-score",
                       title_position = "topleft",
                       legend_height = unit(4, "cm"))) +
  rowAnnotation(label = anno_mark(at = at, labels = labels,
                                  labels_gp = gpar(col = "black", fontsize = 8))
  )

draw(heatmap.b)


## plot selected genes
png(file = "figures/heatmap_selected.png",
    width = 4, 
    height = 8, 
    units = "in", res = 600)

## plot all DE + selected
png(file = "figures/heatmap_allDE_selected.png",
    width = 4, 
    height = 8, 
    units = "in", res = 600)


draw(heatmap.b)

dev.off()
#
seekViewport("annotation_empty_1")
loc1 = deviceLoc(x = unit(0, "npc"), y = unit(0, "npc"))
loc2 = deviceLoc(x = unit(1, "npc"), y = unit(1, "npc"))

####Condition labels

#Condition label 1


grid.rect(x = (loc2$x - loc1$x)*(end_index_body)/2/ncol(m.z),
          y = 0,
          width = (loc2$x - loc1$x)*(number_of_body)/ncol(m.z), 
          height = (loc2$y - loc1$y)/2,
          just = c("center", "bottom"),
          gp = gpar(fill = alpha(cbPalette[1], 0.5),
                    col = alpha(cbPalette[1], 0.5)
          )
)
grid.text(expression("Body"), 
          x = (loc2$x - loc1$x)*(end_index_body)/2/ncol(m.z),
          y = 0.35,
          just = c("center", "top"),
          gp = gpar(fontsize = 11,
                    col = "black"))

#Condition label 2

grid.rect(x = (loc2$x - loc1$x)*(end_index_body + 
                                   end_index_bud)/2/ncol(m.z),
          y = 0,
          width = (loc2$x - loc1$x)*(number_of_bud)/ncol(m.z), 
          height = (loc2$y - loc1$y)/2,
          just = c("center", "bottom"),
          gp = gpar(fill = alpha(cbPalette[2], 0.5),
                    col = alpha(cbPalette[2], 0.5)
          )
)
grid.text(expression("Bud"), 
          x = (loc2$x - loc1$x)*(end_index_body + 
                                   end_index_bud)/2/ncol(m.z),
          y = 0.35,
          just = c("center", "top"),
          gp = gpar(fontsize = 11))





###Top label gaps

#Vertical lines
grid.rect(x = end_index_body/ncol(m.z),
          y = 0,
          height = (loc2$y - loc1$y)/2,
          width = unit(0.03, "inches"),
          just = c("center", "bottom"),
          gp = gpar(fill = "white", 
                    col = "white", 
                    lwd = 1
          ))


dev.off()

```

